experiments:
  longer_minimal:
    name: "Longer Minimal - More psychological evolution"
    
    baseline_experiment:
      agents:
        - type: "rational"
          count: 1
        - type: "loss_averse"
          count: 1
          loss_coefficient: 2.25
      tournaments:
        rounds_per_match: 10    # More rounds to see patterns
        replications: 2         # Multiple tests for reliability
    
    emergent_experiment:
      population_size: 3          # 3 agents for more complex dynamics
      generations: 3              # Multiple generations to see evolution
      interactions_per_generation: 3  # More interactions per generation
      rounds_per_interaction: 10      # Longer interactions for relationship building
      initial_psychology: "neutral"
    
    contagion_experiment:
      population_size: 3
      seed_agents:
        - type: "paranoid"
          count: 1
          trust_level: 0.1
          loss_sensitivity: 3.0
      
      contagion_parameters:
        base_transmission_rate: 0.1
        influence_decay: 0.95
        trait_mutation_rate: 0.05

  llm_configuration:
    primary_provider: "openai"
    model: "gpt-4o-mini"
    temperature: 0.1
    max_tokens: 200  # Keep responses concise
    fallback_provider: "anthropic"
    
  analysis_settings:
    statistical_significance: 0.05
    effect_size_threshold: 0.3
    confidence_interval: 0.95
    multiple_testing_correction: "bonferroni"
    
  output_settings:
    save_raw_data: true
    generate_visualizations: true
    export_for_publication: true
    real_time_monitoring: true