# config/scaled_up.yaml
experiments:
  rich_psychology_study:
    name: "Rich Psychology - AI Agents Learning Pain and Trust"
    
    baseline_experiment:
      agents:
        - type: "rational"
          count: 3
        - type: "loss_averse"
          count: 3
          loss_coefficient: 2.25
      tournaments:
        rounds_per_match: 50    # More rounds for relationship building
        replications: 3         # Multiple baselines for comparison
    
    emergent_experiment:
      population_size: 8        # 8 agents for rich social dynamics
      generations: 5            # 5 generations to see evolution
      interactions_per_generation: 6  # More interactions
      rounds_per_interaction: 25      # Longer relationships
      initial_psychology: "neutral"
    
    contagion_experiment:
      population_size: 8
      seed_agents:
        - type: "paranoid"
          count: 1
          trust_level: 0.1
          loss_sensitivity: 2.5
        - type: "trusting"
          count: 1
          trust_level: 0.9
          loss_sensitivity: 0.8
      
      contagion_parameters:
        base_transmission_rate: 0.15
        influence_decay: 0.95
        trait_mutation_rate: 0.05

  llm_configuration:
    primary_provider: "openai"
    model: "gpt-4o-mini"
    temperature: 0.1
    max_tokens: 300
    fallback_provider: "anthropic"
    
  analysis_settings:
    statistical_significance: 0.05
    effect_size_threshold: 0.3
    confidence_interval: 0.95
    multiple_testing_correction: "bonferroni"
    
  output_settings:
    save_raw_data: true
    generate_visualizations: true
    export_for_publication: true
    real_time_monitoring: true